import { IMAGE_STORE } from '../../server/imageStore.js';
import { openStore } from '../../server/blobs.js';

const CONTENT_TYPES = {
  jpg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
};

// Public: serves product photos uploaded through the staff page.
//
// Uploaded images are immutable — the staff page mints a new random key for
// every upload rather than overwriting — so these can be cached hard. That
// matters for cost: bandwidth is the largest recurring credit line on this
// site, and an uncached product photo is paid for on every page view.
export async function handler(event) {
  if (event.httpMethod !== 'GET' && event.httpMethod !== 'HEAD') {
    return { statusCode: 405, body: 'Method not allowed.' };
  }

  const raw = (event.path || '').split('/product-images/')[1] || '';
  // Keys are generated by us as hex + extension. Anything else is refused
  // rather than passed to the store.
  const key = decodeURIComponent(raw);
  if (!/^[a-f0-9]{24}\.(jpg|png|webp)$/i.test(key)) {
    return { statusCode: 404, body: 'Not found.' };
  }

  try {
    const store = openStore(event, IMAGE_STORE);
    const blob = await store.get(key, { type: 'arrayBuffer' });

    if (!blob) return { statusCode: 404, body: 'Not found.' };

    const extension = key.split('.').pop().toLowerCase();

    return {
      statusCode: 200,
      headers: {
        'Content-Type': CONTENT_TYPES[extension] || 'application/octet-stream',
        'Cache-Control': 'public, max-age=31536000, immutable',
        // Stops a mislabelled file from being sniffed into something
        // executable by the browser.
        'X-Content-Type-Options': 'nosniff',
      },
      body: Buffer.from(blob).toString('base64'),
      isBase64Encoded: true,
    };
  } catch (error) {
    console.error(
      JSON.stringify({ type: 'product-image-error', message: error?.message || String(error) })
    );
    return { statusCode: 404, body: 'Not found.' };
  }
}
