import { IMAGE_STORE } from '../../server/imageStore.js';
import { openStore } from '../../server/blobs.js';

// Served at the URL the staff page hands out. The key is the last path
// segment, so the function's own URL (which has none) is not listed.
export const config = {
  path: '/product-images/*',
};

const CONTENT_TYPES = {
  jpg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
};

function notFound(status = 404) {
  return new Response(status === 405 ? 'Method not allowed.' : 'Not found.', {
    status,
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}

// Public: serves product photos uploaded through the staff page.
//
// Uploaded images are immutable — the staff page mints a new random key for
// every upload rather than overwriting — so these can be cached hard. That
// matters for cost: bandwidth is the largest recurring credit line on this
// site, and an uncached product photo is paid for on every page view.
export default async function productImage(request) {
  if (request.method !== 'GET' && request.method !== 'HEAD') return notFound(405);

  const raw = new URL(request.url).pathname.split('/product-images/')[1] || '';
  // Keys are generated by us as hex + extension. Anything else is refused
  // rather than passed to the store.
  let key;
  try {
    key = decodeURIComponent(raw);
  } catch {
    return notFound();
  }
  if (!/^[a-f0-9]{24}\.(jpg|png|webp)$/i.test(key)) return notFound();

  try {
    const blob = await openStore(undefined, IMAGE_STORE).get(key, { type: 'arrayBuffer' });
    if (!blob) return notFound();

    const extension = key.split('.').pop().toLowerCase();
    return new Response(request.method === 'HEAD' ? null : blob, {
      status: 200,
      headers: {
        'Content-Type': CONTENT_TYPES[extension] || 'application/octet-stream',
        'Cache-Control': 'public, max-age=31536000, immutable',
        // Stops a mislabelled file from being sniffed into something
        // executable by the browser.
        'X-Content-Type-Options': 'nosniff',
      },
    });
  } catch (error) {
    console.error(
      JSON.stringify({ type: 'product-image-error', message: error?.message || String(error) })
    );
    return notFound();
  }
}
